### ISSUE TITLE
[Bug] Infinite item duplication

### ISSUE THREAD

**Issue by LKD-PIX** [defeatedcrow/HeatAndClimateMod#288] opened 2023-11-12 00:38 UTC
Shift-clicking an item into the GUI of the IBC will duplicate it and will appear in the IBC but not be taken from player inventory.
I have InventoryProfilesNext installed which may also be a culprit in this case, i will report more as i test further!

This works with buckets but also tanks from other mods like mekanism ultimate fluid tank

Before click:
![grafik](https://github.com/defeatedcrow/HeatAndClimateMod/assets/91191200/a1be49a7-853e-4e08-bbdc-5395e1df7aed)

Shift + Left-Click
![grafik](https://github.com/defeatedcrow/HeatAndClimateMod/assets/91191200/3ca31638-325a-4f90-833f-51e1b3add08f)

**Comment by defeatedcrow** [comment] 2023-11-24 18:32
Thank you for your report!

In order to verify this issue, I implemented some fluid container items in HaC and confirmed its operation, but no dupe occurred.
I have temporarily commented out at [059f499](https://github.com/defeatedcrow/HeatAndClimateMod/commit/059f49966e167a10522ca364e7a66e3b9dbb87ca) the feature to address the issue, so this issue will probably be removed in the next update.

**Comment by defeatedcrow** [comment] 2024-05-09 16:02
This bug has been fixed in 71bec7c.

**Closed as completed by defeatedcrow** 2024-05-09 16:02 UTC
