### ISSUE TITLE
Wrong fluid level rendering for Tank Yard multiblock

### ISSUE THREAD

**Issue by Prunoideae** [defeatedcrow/HeatAndClimateMod#145] opened 2020-03-11 14:22 UTC
![2020-03-11_22 20 15](https://user-images.githubusercontent.com/24620047/76426940-aaf48180-63e6-11ea-9354-9fcd04a2a665.png)

Happens when I'm testing HAC's content on 3.3.0.

**Comment by defeatedcrow** [comment] 2020-03-13 11:23
It is correct specification that the current capacity exceeds the tank capacity. (This is to prevent the liquid from being lost when the tank volume is changed.)
Such drawing is a defect. It will be fixed in the next update. 
Thank you for your report.

**Comment by Prunoideae** [comment] 2020-03-13 11:51
I haven't changed the size of tank after building it, it comes almost full when filled with 30,000 mB or so, in comparison to a 4.9*10^9 mB tank capacity. The main problem here is that the fluid level calculation is seemed to be errored here.

**Comment by defeatedcrow** [comment] 2020-03-14 10:15
A similar bug could not be reproduced.
The verification environment seems to have other effects (for example, problems syncing the server and client).
Once we find the cause, we start fixing it, but for now there is no way to start it.

**Comment by Prunoideae** [comment] 2020-03-14 10:50
I'm quite confused... It seems like most of the bug happened in my modpack couldn't be reproduced here...
Maybe it's because I made heavy modification on the source code of mods(except HAC) in my modpack, and some working code interfered the render logic here...

**Comment by defeatedcrow** [comment] 2020-03-15 04:57
Mod support is limited to the state released by the author (not limited to this mod), and if a third party modifies it, support will be difficult. (Modifications should be done at your own risk.) Mods are not guaranteed to work in all environments.
This case is clearly out of warranty. 

In this case, the information is scarce and it is impossible to reproduce it cause I'm not a psychic and I can't see on your desk. So it is impossible to correct it. If the cause is found and it is a bug by HaC, I'll fix it.

**Closed as completed** 2020-05-02 09:44 UTC
